spring.application.name=produdoro

server.servlet.context-path=/produdoro/api
server.port=8080

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=alpha
# Substitua <db_password> pela sua senha real (sem os sinais de < >)
spring.data.mongodb.uri=mongodb+srv://janebeatriz26_db_user:mvac0803@wakanda.jcj9jrr.mongodb.net/produdoro?retryWrites=true&w=majority&appName=Wakanda